import os

DHAN_CLIENT_ID = os.environ.get("DHAN_CLIENT_ID", "")
DHAN_ACCESS_TOKEN = os.environ.get("DHAN_ACCESS_TOKEN", "")

MAX_CAPITAL_PER_TRADE_PCT = 0.02
STOP_LOSS_PCT = 0.50
TARGET_PCT = 0.90
MAX_OPEN_LEGS = 3
MIN_OI = 500_000
MIN_DELTA = 0.25
MAX_DELTA = 0.45
MIN_IVR = 40
MAX_BID_ASK_SPREAD_PCT = 0.005

NIFTY_UNDERLYING_ID = 13
BANKNIFTY_UNDERLYING_ID = 25

OLLAMA_MODEL = "llama3.2:3b"
OLLAMA_URL = "http://localhost:11434/api/generate"

NIFTY_LOT_SIZE = 25
BANKNIFTY_LOT_SIZE = 15